import cntl from 'cntl';

export const title = cntl`
    font-bold
    text-gray-900
    dark:text-gray-100
    text-7xl
    md:text-8xl
    leading-none
    relative
    before:block
    before:w-full
    before:h-full
    before:text-7xl
    before:md:text-8xl
    before:text-transparent
    before:bg-clip-text
    before:bg-gradient-to-r
    before:from-blue-500
    before:to-blue-800
    before:text-opacity-90
    before:content-[attr(data-name)]
    before:absolute
    before:top-0
    before:left-0
    before:z-0
    before:-translate-x-0.5
    before:-translate-y-0.5
    after:block
    after:w-full
    after:h-full
    after:text-7xl
    after:md:text-8xl
    after:text-transparent
    after:bg-clip-text
    after:bg-gradient-to-b
    after:from-red-500
    after:to-red-800
    after:text-opacity-90
    after:content-[attr(data-name)]
    after:absolute
    after:top-0
    after:left-0
    after:z-0
    after:translate-x-0.5
    after:translate-y-0.5
`;
